### ISSUE TITLE
[Task] Creation of System Models

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#1]
# Model Task
# Tasks
- [x] Generic User Model
- [x] Admin User Model
- [x] General User Model
- [x] Organisation Model
- [x] NOK Model
# Constraints
- Follow DJANGO User Documentation
# Reference
 [ER Diagram](https://app.diagrams.net/#G1lUoqgoIoFAm2rXTmo-jSfy9cwIurWMdN#%7B%22pageId%22%3A%228NDev13LSA-EnVivUqYl%22%7D)
