### ISSUE TITLE
[General User] Manage Profile

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#10]
# Viewing all accounts 
## User Story
AS AN admin
I WANT TO be able to update the information on my profile
SO THAT I can update my details
OR my NOK details

## Tasks
- [x] Get User API
- [x] Update User API
- [x] Update User NOK API
- [x] Profile View
