### ISSUE TITLE
[All] Change Password Feature

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#4]
# Change Password Feature
## User Story
AS A USER (Admin, Organisation, General User)
I WANT TO be able to change my password
SO THAT I can prevent constant access to my account by others

## Tasks
- [x] Change password API
- [x] Database to be updated with a new password
- [x] Logout user
- [x] Redirects to /login after password change

## Dependents
#1 
#2 
#3
