### ISSUE TITLE
[All] Reset Password Feature

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#5]
# Reset Password Feature
## User Story
AS A USER (Admin, Organisation, General User)
I WANT TO reset my password when I forget it
SO THAT I can access the application's functionalities

## Tasks
- [x] Reset password API
- [x] Rest password page
- [x] Update temporary password onto database
- [x] Redirects to /login after successful reset

## Dependent
#2 
#4
