### ISSUE TITLE
[Admin] View all Organisations and general users

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#6]
# Viewing all accounts 
## User Story
AS AN admin
I WANT TO view all organisations and general user accounts in the system
SO THAT I can approve/ reject the organisation's account creation
OR delete organisations and general user accounts

## Tasks
- [x] Get all organisation API
- [x] Get all user API
- [x] Update organisation approval status API
- [x] Delete organisation API
- [x] Delete user API
- [x] Admin Dashboard to view
