### ISSUE TITLE
[Admin] Approve or Reject Organisation's Events

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#7]
# Manage Organisation's Events
## User Story
AS AN admin
I WANT TO view all of the organisation's event
SO THAT I can approve or reject the organisation's event

## Tasks
- [x] Get all events API
- [x] Update event approval status API
- [x] Admin event page view
