### ISSUE TITLE
[Organisation] Manage Volunteer Event

### ISSUE THREAD

**Issue by JiaJun8899** [JiaJun8899/ict3x03-project#9]
# Manage Volunteer Event
## User Story
AS AN organisation
I WANT TO view all of my events
SO THAT I can view general users who signed up for it
OR update details for it
OR delete the event IF it is rejected

## Tasks
- [x] Get all events by Organisation API
- [x] Get all user sign up by Event API
- [x] Update event API
- [x] Delete event API
- [x] Organisation Event View
